version: "3.9"
services:
  ddcapi:
    image: ddcapi:testv2
    build: .
    ports:
    - "8080:8080"
    environment:
       ConnectionStrings__PostgresConnection: ${CONNECTION_STRING}
       AppSettings__Token: ${JWT_TOKEN}
       APpSettings__Issuer: ${JWT_ISSUER}
       AppSettings__Audience: ${JWT_AUDIENCE}